### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AvidCoder101**
I have added changes to the README.md

### CODE REVIEW

**Comment by AvidCoder101** [comment]
@all-contributors please add @AvidCoder101 for content and contentManagement

**Comment by AvidCoder101** [comment]
@all-contributors please add @CodingSpecies for content and doc

**Comment by NS007-dev** [comment]
@all-contributors please add @all-contributors for projectM

**Comment by NS007-dev** [comment]
@all-contributors please add @all-contributors for projectManagement

**Pull request merged**
